In [2]:
import os
import csv
import sys
import scipy.optimize as opt
import scipy.stats as stat
from operator import itemgetter
import random
import numpy as np
import numpy.ma as ma
import numpy.linalg as la

In [5]:
modulef = 'C:/Users/koolk/Desktop/brain_diffusion/brain_diffusion/'
sys.path.insert(0, modulef)
from msd import fillin2, MSD_iteration, vectorized_MMSD_calcs

In [3]:
df = np.genfromtxt('../sample_data.csv', delimiter=",")
df = np.delete(df, 0, 1)[:, 0:5]

In [6]:
#generating a sample dataset

n = 6
p = 2
df = np.zeros((p*n, 12))
for i in range(1, p+1):
    df[(i-1)*n:i*n, 0] = np.ones(n) + i - 1
    df[(i-1)*n:i*n, 1] = np.ones(n) + i - 1
    df[(i-1)*n:i*n, 2] = np.linspace(0, 10, n) + 2 + i
    df[(i-1)*n:i*n, 3] = np.linspace(0, 10, n) + i
    df[(i-1)*n:i*n, 4] = np.linspace(0, 10, n) + 3 + i
    df[(i-1)*n:i*n, 5] = np.zeros(n)
    df[(i-1)*n:i*n, 6:12] = np.zeros((n, 6))

In [19]:
df[:, 1:5]

array([[  1.,   3.,   1.,   4.],
       [  1.,   5.,   3.,   6.],
       [  1.,   7.,   5.,   8.],
       [  1.,   9.,   7.,  10.],
       [  1.,  11.,   9.,  12.],
       [  1.,  13.,  11.,  14.],
       [  2.,   4.,   2.,   5.],
       [  2.,   6.,   4.,   7.],
       [  2.,   8.,   6.,   9.],
       [  2.,  10.,   8.,  11.],
       [  2.,  12.,  10.,  13.],
       [  2.,  14.,  12.,  15.]])

In [7]:
np.savetxt("../Traj_test_data_1.tif.csv", df, delimiter=",")

In [8]:
folder = '../'
name = 'test_data'
cut = 1
totvids = 1
conversion = (1, 1, 1)

In [9]:
total1, frames, xs_m, ys_m, x_m, y_m = MSD_iteration(folder, name)

In [21]:
geoM2xy, gSEM, SM1x, SM1y, SM2xy = vectorized_MMSD_calcs(frames, total1, xs_m, ys_m)

In [29]:
geoM2xy

array([ 0.        ,  1.38629436,  2.07944154,  2.99573227,  3.4657359 ,
        3.95124372,  4.27666612,  4.60517019,  4.85203026,  5.09986643,
        5.29831737,  0.        ,  0.        ,  0.        ])

In [26]:
SM1y

array([[   0.,    0.],
       [   2.,    2.],
       [   4.,    4.],
       [  10.,   10.],
       [  16.,   16.],
       [  26.,   26.],
       [  36.,   36.],
       [  50.,   50.],
       [  64.,   64.],
       [  82.,   82.],
       [ 100.,  100.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.]])

In [28]:
SM2xy

array([[   0.,    0.],
       [   4.,    4.],
       [   8.,    8.],
       [  20.,   20.],
       [  32.,   32.],
       [  52.,   52.],
       [  72.,   72.],
       [ 100.,  100.],
       [ 128.,  128.],
       [ 164.,  164.],
       [ 200.,  200.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.]])