In [2]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from trajectory_visualization import plot_trajectory, sidebyside, shift_trajectory, overlay, shift_trajectory3D
from trajectory_visualization import plot_trajectories3D, plot_3Doverlay, plot_MSDorDeff, plot_MeanMSDorDeff, randtraj, multrandtraj
from trajectory_visualization import randtraj2, plot_Mean2DMSDsorDeff, plot_MSDorDeffLR, LRfor3D2D, fillin, prettify
from random_traj import randaniso, randconv, multrandaniso, multrandconv, randsamp, multrandsamp, randall, multrandall
from random_traj import randanisorot, multrandanisorot
from ellipsoid import maxtraj, mvee, plot_mvee, plot_mveeoverl, rotmat, rotmat2, plot_mveeoverl2
from ellipsoid import ellipsax, MSDS, andiff, plot_anisoMSDS, plot_anisodiff
from ellipsoid import extrema, enclosed_MSD

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import scipy.optimize as opt
from mpl_toolkits.mplot3d import Axes3D
from operator import itemgetter
import random
import numpy as np
import numpy.linalg as la
from mpl_toolkits.mplot3d import Axes3D

pi = np.pi
sin = np.sin
cos = np.cos

In [3]:
# Type in datasets you would like to combine.  Adjust totvids to reflect the total number of videos. Also type in the
# umppx and fps in the conversion dictionary.

conversion = dict() #First element is the umppx, second is fps

conversion[1] = (0.59, 3.71, 1.5)
conversion[2] = (0.59, 3.71, 1.5)
conversion[3] = (0.59, 3.71, 1.5)
conversion[4] = (0.59, 3.71, 1.5)
conversion[5] = (0.59, 3.71, 1.5)

trajectory = dict()

trajectory[1] = np.genfromtxt('../../sample_data/100nm_NPs/3DVideo_CON_1.csv',
            delimiter =",")
trajectory[2] = np.genfromtxt('../../sample_data/100nm_NPs/3DVideo_CON_2.csv',
            delimiter =",")
trajectory[3] = np.genfromtxt('../../sample_data/100nm_NPs/3DVideo_CON_3.csv',
            delimiter =",")
trajectory[4] = np.genfromtxt('../../sample_data/100nm_NPs/3DVideo_CON_4.csv',
            delimiter =",")
trajectory[5] = np.genfromtxt('../../sample_data/100nm_NPs/3DVideo_CON_5.csv',
            delimiter =",")

totvids = 5

for num in range(1, totvids + 1):
    
    #Remove titles from columns
    #trajectory[num]=np.delete(trajectory[num], 0,0)
    #Remove the number column from dataset
    trajectory[num]=np.delete(trajectory[num],0,1)

In [4]:
final = dict()
tots = dict()

for num in range(1, totvids + 1):
    (final[num], tots[num]) = prettify(trajectory[num], 28, 28, conversion[num][0], conversion[num][1], conversion[num][2])
    

In [5]:
parts = dict()
lehi = dict()

for num in range(1, totvids + 1):
    parts[num] = tots[num]
    lehi[num] = final[num][1]
    counter = 1

    while counter < parts[num]:
        counter = counter + 1
        lehi[num] = np.append(lehi[num], final[num][counter], axis=0)

for num in range(2, totvids + 1):
    lehi[num][:,0] = lehi[num][:,0] + max(lehi[num-1][:, 0])        
        
nephi = lehi[1]
counter = 1

while counter < totvids:
    counter = counter + 1
    nephi = np.append(nephi, lehi[counter], axis=0)

In [6]:
# Now for a plotting function, as modified from Testing_Tracking_Software

# Creates an array 'particles' that contains the particle number at each frame.
particles = nephi[:, 0]
position = nephi[:, 5:5+4]
total = int(max(particles))
total1 = total + 1
path = dict()

# Creates an array for each trajectory containing all xyz data
for num in range(1, total1):

    hold = np.where(particles == num)
    itindex = hold[0]
    min1 = min(itindex)
    max1 = max(itindex)
    path[num] = (position[min1:max1, :])

# Creates figure
fig = plt.figure(figsize=(24, 18), dpi=80)
ax = fig.add_subplot(111)
# ax.set_title('Particle Trajectories', x=0.5, y=1.15)

# Plots individual trajectories
for num in range(1, total1):

    ax.plot(path[num][:, 0], path[num][:, 1], label='Particle {}'.format(num), linewidth=5)

axbox = ax.get_position()

legunit = max(nephi[:,0])
#ax.legend(loc=(0.85, 0.96-0.0273*legunit), prop={'size': 20})
ax.locator_params(nbins=6)

# A few adjustments to prettify the graph
for item in ([ax.xaxis.label, ax.yaxis.label] +
             ax.get_xticklabels() + ax.get_yticklabels()):
    item.set_fontsize(20)

ax.title.set_fontsize(35)
ax.tick_params(direction='out', pad=3)
plt.gca().xaxis.set_major_formatter(mpl.ticker.FormatStrFormatter('%.{}f um'.format(1)))
plt.gca().yaxis.set_major_formatter(mpl.ticker.FormatStrFormatter('%.{}f um'.format(1)))

dim = 2
plt.gca().set_xlim([-dim, dim])
plt.gca().set_ylim([-dim, dim])

# Save your figure
plt.savefig('{}.png'.format('Edward_trajectories'), bbox_inches='tight')

plt.show()

In [7]:
nephi[:, 0]

array([   1.,    1.,    1., ...,  140.,  140.,  140.])

In [8]:
def plot_Mean1DMSDsorDeff(traj, n1, n2, n3, dec1, dec2, datatype, filename, limit1, limit2, tick1, tick2):
    """
    Plots the MSDs or Deffs from a trajectory dataset.

    n1: particle numbers (typically 0)
    n2: time (typically 1)
    n3: MSDs or Deffs (11 or 15 typically)
    """

    # Creates an array 'particles' that contains the particle number at each frame.
    particles = traj[:, n1]
    total = int(max(particles))
    total1 = total + 1
    rawtime = traj[:, n2]
    bow = traj.shape[0]
    raw2DMSDs = np.zeros((bow, 4))
    raw2DMSDs[:, 0] = traj[:, n3]
    raw2DMSDs[:, 1:4] = traj[:, n3 + 3:n3 + 6]
    MSD = dict()
    time = dict()

    # Creates an array for each trajectory containing all xyz data
    for num in range(1, total1):

        hold = np.where(particles == num)
        itindex = hold[0]
        min1 = min(itindex)
        max1 = max(itindex)
        MSD[num] = (raw2DMSDs[min1+2:max1, :])
        time[num] = (rawtime[min1+2:max1])

    MMSD = MSD[1]
    for num in range(2, total1):
        MMSD = MMSD + MSD[num]
    MMSD = MMSD/total1

    # Creates figure
    fig = plt.figure(figsize=(24, 18), dpi=80)
    ax = fig.add_subplot(111)
    # ax.set_title('Particle Trajectories', x=0.5, y=1.15)

    ax.plot(time[1][:], MMSD[:, 0], linewidth=10, label='2D')
    ax.plot(time[1][:], MMSD[:, 1], linewidth=10, label='1D x')
    ax.plot(time[1][:], MMSD[:, 2], linewidth=10, label='1D y')

    # A few adjustments to prettify the graph
    for item in ([ax.xaxis.label, ax.yaxis.label] +
                 ax.get_xticklabels() + ax.get_yticklabels()):
        item.set_fontsize(70)

    xmajor_ticks = np.arange(0, limit1, tick1)
    ymajor_ticks = np.arange(0, limit2, tick2)

    ax.set_xticks(xmajor_ticks)
    ax.set_yticks(ymajor_ticks)
    ax.title.set_fontsize(70)
    ax.set_xlabel('Time (s)', fontsize=95)
    ax.set_ylabel(datatype, fontsize=95)
    ax.tick_params(direction='out', pad=16)
    ax.legend(loc=(0.65, 0.05), prop={'size': 70})
    plt.gca().xaxis.set_major_formatter(mpl.ticker.FormatStrFormatter('%.{}f'.format(dec1)))
    plt.gca().yaxis.set_major_formatter(mpl.ticker.FormatStrFormatter('%.{}f'.format(dec2)))

    plt.gca().set_xlim([0, limit1])
    plt.gca().set_ylim([0, limit2])

    # Save your figure
    plt.savefig('{}.png'.format(filename), bbox_inches='tight')
    return MMSD

In [30]:
one1 = plot_Mean2DMSDsorDeff(nephi, 0, 15, 8, 0, 1, 'MSD (um^2)', 'Edward_MSD_1', 8, 0.51, 1, 0.1)
plt.show()

In [32]:
one2 = plot_Mean2DMSDsorDeff(nephi, 0, 15, 16, 0, 2, 'Deff (um^2/s)', 'Edward_Deff_1', 8, 0.041, 1, 0.01)
plt.show()

In [24]:
def find_nearest(array,value):
    idx = (np.abs(array-value)).argmin()
    return array[idx]

In [34]:
#This cell gives a few steps to finding the desired 2D diffusion coefficient based on the input time.

#Desired time (normally 1s)
desired = 1.0

time1 = lehi[1][:, 15]
x1 = find_nearest(time1, 1.0)
x2 = np.where(time1 == x1)[0][0]
Deff = one2[x2][0]
Deff

0.017413380113460053

In [27]:
one2

array([[ 0.02195151,  0.01833102,  0.025572  ,  0.02462526],
       [ 0.0158601 ,  0.01342107,  0.01829912,  0.01721526],
       [ 0.01687544,  0.01427776,  0.01947312,  0.01359756],
       [ 0.01682564,  0.01464509,  0.01900619,  0.01578181],
       [ 0.01836809,  0.01777301,  0.01896318,  0.01550395],
       [ 0.02107314,  0.02220909,  0.01993719,  0.0161981 ],
       [ 0.02063516,  0.01884506,  0.02242525,  0.01514266],
       [ 0.03023151,  0.02379705,  0.03666596,  0.01379723],
       [ 0.02883689,  0.023046  ,  0.03462779,  0.0128848 ],
       [ 0.02715242,  0.02146867,  0.03283616,  0.01507274],
       [ 0.02465902,  0.02029165,  0.02902639,  0.0137121 ],
       [ 0.02386187,  0.02136496,  0.02635878,  0.01370959],
       [ 0.02446278,  0.02292425,  0.02600131,  0.01314831],
       [ 0.02569343,  0.02213548,  0.02925137,  0.01284618],
       [ 0.02458061,  0.02091831,  0.02824292,  0.01157283],
       [ 0.02372279,  0.0202645 ,  0.02718108,  0.01254516],
       [ 0.02707355,  0.

In [33]:
one2

array([[ 0.02284276,  0.02195151,  0.02147814,  0.02509863],
       [ 0.01631182,  0.0158601 ,  0.01531817,  0.01775719],
       [ 0.01578282,  0.01687544,  0.01393766,  0.01653534],
       [ 0.01647769,  0.01682564,  0.01521345,  0.017394  ],
       [ 0.01741338,  0.01836809,  0.01663848,  0.01723357],
       [ 0.01944813,  0.02107314,  0.01920359,  0.01806764],
       [ 0.01880432,  0.02063516,  0.01699386,  0.01878395],
       [ 0.02475342,  0.03023151,  0.01879714,  0.0252316 ],
       [ 0.02351953,  0.02883689,  0.0179654 ,  0.02375629],
       [ 0.02312586,  0.02715242,  0.01827071,  0.02395445],
       [ 0.02101005,  0.02465902,  0.01700187,  0.02136925],
       [ 0.02047778,  0.02386187,  0.01753728,  0.02003419],
       [ 0.02069129,  0.02446278,  0.01803628,  0.01957481],
       [ 0.02141101,  0.02569343,  0.01749083,  0.02104877],
       [ 0.02024469,  0.02458061,  0.01624557,  0.01990787],
       [ 0.01999692,  0.02372279,  0.01640483,  0.01986312],
       [ 0.02202108,  0.